---
title: "Summary of Yelp Users"
author: "ES"
date: "August 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Installing packages, setting directory

```{r, echo=FALSE}
rm(list=ls())

library(jsonlite)
library(magrittr)
library(Hmisc) # Summarize data using describe()

setwd("C:/Users/SV Tech Holdings/Documents/NYU MSBA/Capstone/Data/Data")

```

#### Reading the Yelp - User JSON file

```{r users, echo=FALSE,eval=FALSE}
# read in individual JSON lines
#json_file <- "yelp_academic_dataset_user.json"

# turn it into a proper array by separating each object with a "," and
# wrapping that up in an array with "[]"'s.

#data_user <- fromJSON(sprintf("[%s]", paste(readLines(json_file), collapse=","))) # flattening and reading into dataframe
#dput(data_user,file="data_user.txt") # converting JSON to txt file

```

#### Extracting friends list and saving as RDS file for future retrieval

```{r echo=FALSE,eval=FALSE}
# Save the friends list as a separate object
friends_list=data_user$friends
names(friends_list)=data_user$user_id # assigning user_ids to each vector in list

#Saving friends list in a easy to retrieve R object 
saveRDS(friends_list,"friends_list.rds") # save list for retrieval later with readRDS()

# Cleaning environment
rm(list=ls())
```

#### Reading RDS file and converting to list

```{r echo=FALSE}
friends_list=as.matrix(readRDS("friends_list.rds"))

# Converting to data frame and counting no of friends per user IDs
user_friends=data.frame(rownames(friends_list)) %>% setNames("UserIDs")
user_friends$No_of_Friends=do.call(rbind,lapply(friends_list[,1],function(x) length(x)))
user_friends$Friends_IDs=friends_list[,1]

#write.csv(user_friends,"user_friends.csv")

```

#### Summarize number of friends for each UserID

```{r,echo=FALSE,eval=FALSE}
summary(user_friends$No_of_Friends,digits=0)
plot(user_friends$No_of_Friends,main="Number of Friends per User",ylab="No of Friends")
```

```{r}
#friends_list1=lapply(friends_list, `length<-`, max(lengths(friends_list))) # running out of memory
#a=unlist(friends_list,use.names = F,recursive = T)
